[tool.poetry]
name = "ciphers"
version = "0.1.0"
description = "Simple cipher algorithms implementations for educational purposes."
authors = ["João Paulo Taylor Ienczak Zanette <jpaulotiz@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7"

[tool.poetry.dev-dependencies]
